export const AdminReq = [
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
  {
    name: "ASD",
    Dept: "CSE",
    faculty: "Assitant Professor",
    specialist: "Wireless Network",
    scret: "DA123",
  },
];
